<a href="https://colab.research.google.com/github/ugrcnylmz/Assingment/blob/main/Assignment_01_Student.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" 
alt="CLRSWY"></p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:100%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#060108; font-size:200%; text-align:center; border-radius:10px 10px;">Data Analysis with Python</p>

![Image_Assignment](https://i.ibb.co/cY9HhF7/bnote-assignment.gif)

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#4d77cf; font-size:200%; text-align:center; border-radius:10px 10px;">Assignment 01 (NumPy & Pandas Basics)</p>

<a id="toc"></a>

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Content</p>

* [NUMPY SECTION](#0)
* [PANDAS SECTION](#1)


**In this assignment you will start off with Numpy Exercises and then complete the whole Exercise with Pandas questions. All the subjects related to questions here already covered in preclass materials and in-class sessions. So good luck!**

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Numpy Section</p>

<a id="0"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

### 1. Import NumPy Library.

In [1]:
# YOUR CODE IS HERE
import numpy as np

### 2. Create an array from my_list = [5, 10, 15, 20, 25]

In [8]:
# YOUR CODE IS HERE
my_list = np.array([5, 10, 15, 20, 25])

### 3. Generate an array of 5x5 with zeros. 

In [9]:
# YOUR CODE IS HERE
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### 4. Generate an array of 4x4 with ones and assign data type as int.

In [11]:
# YOUR CODE IS HERE
np.ones((4,4),dtype = int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

### 5. Make all the values of the array above with the value of 7.

In [13]:
# YOUR CODE IS HERE
np.ones((4,4),dtype = int)*7

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

### 6. Create the previous array above by full() method.

In [14]:
# YOUR CODE IS HERE
np.full((4,4), "7")


array([['7', '7', '7', '7'],
       ['7', '7', '7', '7'],
       ['7', '7', '7', '7'],
       ['7', '7', '7', '7']], dtype='<U1')

### 7. Create an array of even integers from 2 to 16 (inclusive). 

In [15]:
# YOUR CODE IS HERE
np.arange(2, 17, 2)


array([ 2,  4,  6,  8, 10, 12, 14, 16])

### 8. Create a 5x5 matrix with the values between 0 to 25 (exclusive).

In [80]:
# YOUR CODE IS HERE
np.arange(25).reshape(5,5)


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### 9. Create a 5x5 matrix with the values between 0 to 25 (exclusive) using linspace method.

In [33]:
# YOUR CODE IS HERE
np.linspace(0, 25,26, dtype = "int")

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25])

### 10. Create randomly 5 numbers with numpy.

In [34]:
# YOUR CODE IS HERE
np.random.rand(5)


array([0.76673306, 0.92727728, 0.66555897, 0.41005759, 0.99270379])

### 11. Create an array of 5*5 shape and fills it with random values as per the standard normal distribution.

In [35]:
# YOUR CODE IS HERE
np.random.rand(5,5)


array([[0.98582873, 0.46935565, 0.88423401, 0.91445626, 0.29607583],
       [0.0087495 , 0.3288828 , 0.60358236, 0.22311079, 0.02240689],
       [0.90310738, 0.52981815, 0.72915668, 0.64224104, 0.27156192],
       [0.58500791, 0.10223395, 0.20781494, 0.55481721, 0.69535904],
       [0.75821525, 0.93583249, 0.55676067, 0.44204679, 0.119033  ]])

### 12. Create a 3*4 array of random int numbers between 20 and 50.

In [49]:
# YOUR CODE IS HERE
np.random.randint(10, size = (3, 4))


array([[5, 5, 3, 5],
       [8, 1, 8, 3],
       [7, 4, 2, 2]])

### 13. Create an array named "ranarr"consisting of randomly 48 numbers and reshape this array with the shape of 6x8 in different ways.

In [52]:
# YOUR CODE IS HERE
arr = np.arange(48)
ranarr = np.random.rand(6,8)
ranarr

array([[0.1176371 , 0.85659673, 0.91884857, 0.66710951, 0.74324555,
        0.12495491, 0.55995129, 0.04662703],
       [0.64306228, 0.47438211, 0.1542767 , 0.49396904, 0.92669167,
        0.57258093, 0.54612068, 0.22857852],
       [0.40982576, 0.32129596, 0.41532185, 0.66996751, 0.36236611,
        0.61160307, 0.90860271, 0.13089593],
       [0.85169541, 0.17757056, 0.59981274, 0.18331865, 0.16082988,
        0.00365803, 0.68408702, 0.31590832],
       [0.69901958, 0.62277205, 0.4812614 , 0.46347915, 0.29182347,
        0.67993117, 0.50024561, 0.18676582],
       [0.21552791, 0.60808254, 0.5102941 , 0.72231906, 0.17270823,
        0.92037721, 0.46127991, 0.72804612]])

In [53]:
# YOUR CODE IS HERE (RESHAPING WITH NUM)
ranarr.shape


(6, 8)

In [54]:
# YOUR CODE IS HERE (RESHAPING WITH -1)
ranarr.reshape(-1, 48)


array([[0.1176371 , 0.85659673, 0.91884857, 0.66710951, 0.74324555,
        0.12495491, 0.55995129, 0.04662703, 0.64306228, 0.47438211,
        0.1542767 , 0.49396904, 0.92669167, 0.57258093, 0.54612068,
        0.22857852, 0.40982576, 0.32129596, 0.41532185, 0.66996751,
        0.36236611, 0.61160307, 0.90860271, 0.13089593, 0.85169541,
        0.17757056, 0.59981274, 0.18331865, 0.16082988, 0.00365803,
        0.68408702, 0.31590832, 0.69901958, 0.62277205, 0.4812614 ,
        0.46347915, 0.29182347, 0.67993117, 0.50024561, 0.18676582,
        0.21552791, 0.60808254, 0.5102941 , 0.72231906, 0.17270823,
        0.92037721, 0.46127991, 0.72804612]])

## Numpy Indexing and Selection

### Create an array named "mat" in accordence with the desired output below.

In [104]:
# YOUR CODE IS HERE 
mat = np.arange(1,17).reshape(4,4)
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

### 14. Using the array above, write a code that reproduces the desired output shown below.<br>

In [105]:
# YOUR CODE IS HERE 
mat[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

### 15. Get the 1st column (index number 0) of the array above.

In [106]:
# YOUR CODE IS HERE 
mat[0]

array([1, 2, 3, 4])

### 16. Get the values in 2nd row (index number 1) for every 2 step.

In [107]:
# YOUR CODE IS HERE 
mat[3:5,:]

array([[13, 14, 15, 16]])

### 17.Assign 77 to every cell in 3rd column.

In [108]:
# YOUR CODE IS HERE 
mat[:,2:3]=77
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

### 18. (a) Take 2nd row (index number 1) and 1st column (index number 0) , (b) 4th row (index number 3) and 3rd column (index number 2) .

In [109]:
# YOUR CODE IS HERE 
mat[1:2,:3]

array([[ 5,  6, 77]])

### 19. Take between 2nd and last row with step 2 and between 1st and last column with step 2.

In [110]:
# YOUR CODE IS HERE 
mat[::3]

array([[ 1,  2, 77,  4],
       [13, 14, 77, 16]])

## NumPy Operations

### 20. Get the sum of values smaller than 10 and values bigger than 12 in "mat".

In [111]:
# LET US REMEMBER OUR ARRAY OF "mat" 

# YOUR CODE IS HERE 

mat.sum()

408

In [114]:
# LET US FIND THE VALUES SMALLER THAN 10 IN "mat" 

# YOUR CODE IS HERE 
np.array(mat)<10


array([[ True,  True, False,  True],
       [ True,  True, False,  True],
       [ True, False, False, False],
       [False, False, False, False]])

### 21. Get the standard deviation (std) of the result above.

In [115]:
# YOUR CODE IS HERE 
mat.std()


30.004166377354995

### 22. Get the sum of the 2nd column in the original "mat".

In [131]:
# LET US REMEMBER OUR ARRAY OF "mat" 

# YOUR CODE IS HERE 
mat = np.arange(1,17).reshape(4,4)
mat1= mat[:,1:3]
mat1.sum() 


68

In [132]:
# LET OBTAIN THE ORIGINAL ARRAY OF "mat" 

# YOUR CODE IS HERE 

mat = np.arange(1,17).reshape(4,4)

### 23. Get the median, mean and std of 3rd column in "mat".

In [136]:
# LET US REMEMBER OUR ARRAY OF "mat" 

# YOUR CODE IS HERE 
mat2=mat[:,2:3]
np.median(mat2)

9.0

In [137]:
# LET US ASSIGN THE COLUMN WE ARE INTERESTED IN TO A VARIABLE 

# YOUR CODE IS HERE 
mat[:,2:3]


array([[ 3],
       [ 7],
       [11],
       [15]])

In [142]:
# WHAT IF WE ARE INTERESTED IN THE 3RD ROW? 

# YOUR CODE IS HERE 
mat3=mat[2]


In [143]:
# LET US GET MEDIAN VALUE 

# YOUR CODE IS HERE 
np.median(mat3)


10.5

In [141]:
# LET US GET MEAN VALUE 

# YOUR CODE IS HERE 
np.mean(mat3)


10.5

In [144]:
# LET US GET STANDART DEVIATION (std) VALUE 

# YOUR CODE IS HERE 
np.std(mat3)


1.118033988749895

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Pandas Section</p>

<a id="1"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

### Import Pandas Library

In [152]:
import pandas as pd

### Read Salaries.csv and take a look at the first 5 rows, df info and df statistical measurements.*

In [153]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [158]:
# LET US READ Salaries.csv 

# YOUR CODE IS HERE 
df =pd.read_csv('/content/drive/MyDrive/Salaries.csv')

In [159]:
# LET US LOOK AT THE FIRST 5 ROWS 

# YOUR CODE IS HERE 
df.head()


Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN  
1  2011    NaN  San Francisco     NaN  
2  2011    NaN  San Francisco     NaN  
3  2011    NaN  San Francisco     NaN  
4  2011    NaN  San Francisco     NaN

Desired Output:

![image.png](https://i.ibb.co/6BTmGX8/assignment1a.png)

In [162]:
# LET US GET A SAMPLE 

# YOUR CODE IS HERE 
df.sample()


Id       EmployeeName                             JobTitle  BasePay  \
31798  31799  KAMOLPORN GRIFFIN  PUBLIC SERVICE AIDE-HEALTH SERVICES  9491.51   

       OvertimePay  OtherPay  Benefits  TotalPay  TotalPayBenefits  Year  \
31798        11.48       0.0       NaN   9502.99           9502.99  2011   

       Notes         Agency  Status  
31798    NaN  San Francisco     NaN

Desired Output (WATCH OUT! Your output may NOT be the same as the one):

![image.png](https://i.ibb.co/mcsCxxC/assignment1b.png)

In [164]:
# YOUR CODE IS HERE 
df.describe().T

count          mean           std      min        25%  \
Id                148654.0  74327.500000  42912.857795     1.00  37164.250   
BasePay           148045.0  66325.448840  42764.635495  -166.01  33588.200   
OvertimePay       148650.0   5066.059886  11454.380559    -0.01      0.000   
OtherPay          148650.0   3648.767297   8056.601866 -7058.59      0.000   
Benefits          112491.0  25007.893151  15402.215858   -33.89  11535.395   
TotalPay          148654.0  74768.321972  50517.005274  -618.13  36168.995   
TotalPayBenefits  148654.0  93692.554811  62793.533483  -618.13  44065.650   
Year              148654.0   2012.522643      1.117538  2011.00   2012.000   
Notes                  0.0           NaN           NaN      NaN        NaN   
Status                 0.0           NaN           NaN      NaN        NaN   

                       50%         75%        max  
Id                74327.50  111490.750  148654.00  
BasePay           65007.45   94691.050  319275.01  
OvertimePay           0.00    4658.175  245131.88  
OtherPay            811.27    4236.065  400184.25  
Benefits          28628.62   35566.855   96570.66  
TotalPay          71426.61  105839.135  567595.43  
TotalPayBenefits  92404.09  132876.450  567595.43  
Year               2013.00    2014.000    2014.00  
Notes                  NaN         NaN        NaN  
Status                 NaN         NaN        NaN